01

for문의 실행결과를 예측하라.

```
과일 = ["사과", "귤", "수박"]
for 변수 in 과일:
    print(변수)

```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.

# 사과
# 귤
# 수박

02

for문의 실행결과를 예측하라.

```
과일 = ["사과", "귤", "수박"]
for 변수 in 과일:
  print("#####")
```

In [ ]:
# 리스트 내 요소의 개수만큼 "#####"을 출력한다.

# #####
# #####
# #####

03

다음 for 문과 동일한 기능을 수행하는 코드를 작성하세요.

```
for 변수 in ["A", "B", "C"]:
  print(변수)
```

In [ ]:
# ["A", "B", "C"]를 리스트에 담는다.
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["A", "B", "C"]
for 변수 in 리스트:
  print(변수)

# 결과가 동일한 코드
# print("A")
# print("B")
# print("C")

A
B
C

04

for문을 풀어서 동일한 동작을하는 코드를 작성하라.

```
for 변수 in ["A", "B", "C"]:
  print("출력:", 변수)
```

In [ ]:
# ["A", "B", "C"]를 리스트에 담는다.
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["A", "B", "C"]
for 변수 in 리스트:
  print("출력:", 변수)

# 결과가 동일한 코드
# print("출력: ", "A")
# print("출력: ", "B")
# print("출력: ", "C")

출력: A
출력: B
출력: C

05

for문을 풀어서 동일한 동작을 하는 코드를 작성하라.

```
for 변수 in ["A", "B", "C"]:
  b = 변수.lower()
  print("변환:", b)
```

In [ ]:
# ["A", "B", "C"]를 리스트에 담는다.
# b = 변수를 소문자로 변환한다.
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["A", "B", "C"]
for 변수 in 리스트:
  b = 변수.lower()
  print("변환:", b)

변환: a
변환: b
변환: c

06

다음 코드를 for문으로 작성하라.

```
변수 = 10
print(변수)
변수 = 20
print(변수)
변수 = 30
print(변수)
```

In [ ]:
# 변수 10, 20, 30을 리스트에 담는다.
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [10, 20, 30]
for 변수 in 리스트:
  print(변수)

10
20
30

07

다음 코드를 for문으로 작성하라.

```
print(10)
print(20)
print(30)
```

In [ ]:
# 변수 10, 20, 30을 리스트에 담는다.
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [10, 20, 30]
for 변수 in 리스트:
  print(변수)

10
20
30

08

다음 코드를 for문으로 작성하라.

```
print(10)
print("-------")
print(20)
print("-------")
print(30)
print("-------")
```

In [ ]:
# 변수 10, 20, 30을 리스트에 담는다.
# 리스트 내 요소의 개수만큼 "-------"을 출력한다.
리스트 = [10, 20, 30]
for 변수 in 리스트:
  print("-------")

-------
-------
-------

09

다음 코드를 for문으로 작성하라.

```
print("++++")
print(10)
print(20)
print(30)
```

In [ ]:
# 변수 10, 20, 30을 리스트에 담는다.
# "++++" 우선 출력하고, 리스트 내 요소를 하나씩 출력한다.
리스트 = [10, 20, 30]
print("++++")
for 변수 in 리스트:
  print(변수)

++++
10
20
30

10

다음 코드를 for문으로 작성하라.

```
print("-------")
print("-------")
print("-------")
print("-------")
```

In [ ]:
# range() : 범위
# range() 내 숫자만큼 "-------"을 출력한다.
for 변수 in range(4):
  print("-------")

-------
-------
-------
-------

11

다음과 같이 판매가가 저장된 리스트가 있을 때 부가세가 포함된 가격을 for 문을 사용해서 화면에 출력하라. 단 부가세는 10원으로 가정한다.

```
리스트 = [100, 200, 300]
```
```
110
210
310
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [100, 200, 300]
for 변수 in 리스트:
  # 부가세 10 포함 (+ 10)
  print(변수 + 10)

110
210
310

12

for 문을 사용해서 리스트에 저장된 값을 다음과 같이 출력하라.
```
리스트 = ["김밥", "라면", "튀김"]
```
```
오늘의 메뉴: 김밥
오늘의 메뉴: 라면
오늘의 메뉴: 튀김
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["김밥", "라면", "튀김"]
for 변수 in 리스트:
  print("오늘의 메뉴: " + 변수)

오늘의 메뉴: 김밥
오늘의 메뉴: 라면
오늘의 메뉴: 튀김

13

리스트에 주식 종목이름이 저장돼 있다.

```
리스트 = ["SK하이닉스", "삼성전자", "LG전자"]
```

저장된 문자열의 길이를 다음과 같이 출력하라.
```
6
4
4
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["SK하이닉스", "삼성전자", "LG전자"]
for 변수 in 리스트:
  # len() : 길이
  # 변수의 길이를 출력한다.
  print(len(변수))

6
4
4

14

리스트에는 동물이름이 문자열로 저장돼 있다.

```
리스트 = ['dog', 'cat', 'parrot']
```

동물 이름과 글자수를 다음과 같이 출력하라.

```
dog 3
cat 3
parrot 6
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['dog', 'cat', 'parrot']
for 변수 in 리스트:
  # len() : 길이
  # 변수, 변수의 길이를 출력한다.
  print(변수, len(변수))

dog 3
cat 3
parrot 6

15

리스트에 동물 이름 저장돼 있다.

```
리스트 = ['dog', 'cat', 'parrot']
```
for문을 사용해서 동물 이름의 첫 글자만 출력하라.
```
d
c
p
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['dog', 'cat', 'parrot']
for 변수 in 리스트:
  # 변수의 첫 글자(인덱스 0번)를 출력한다.
  print(변수[0])

d
c
p

16

리스트에는 세 개의 숫자가 바인딩돼 있다.

```
리스트 = [1, 2, 3]
```

for문을 사용해서 다음과 같이 출력하라.
```
3 x 1
3 x 2
3 x 3
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [1, 2, 3]
for 변수 in 리스트:
  # 변수를 문자열로 변환해 출력한다.
  print("3 * " + str(변수))

3 * 1
3 * 2
3 * 3

17

리스트에는 세 개의 숫자가 바인딩돼 있다.

```
리스트 = [1, 2, 3]
```
for문을 사용해서 다음과 같이 출력하라.
```
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [1, 2, 3]
for 변수 in 리스트:
  # 변수를 문자열로 변환하고, 3 * 변수의 결괏값을 출력한다.
  print("3 * " + str(변수) + " = ", 3 * 변수)

3 * 1 =  3
3 * 2 =  6
3 * 3 =  9

18

리스트에는 네 개의 문자열이 바인딩돼 있다.

```
리스트 = ["가", "나", "다", "라"]
```
for문을 사용해서 다음과 같이 출력하라.
```
나
다
라
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["가", "나", "다", "라"]
# 리스트의 두 번째 요소부터 출력한다.
for 변수 in 리스트[1:]:
  print(변수)

# range()를 사용한 방법
for 변수 in range(1, len(리스트)):
  print(리스트[변수])

나
다
라
나
다
라

19

리스트에는 네 개의 문자열이 바인딩돼 있다.
```
리스트 = ["가", "나", "다", "라"]
```
for문을 사용해서 다음과 같이 출력하라.
```
가
다
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["가", "나", "다", "라"]
# 리스트의 홀수 요소를 출력한다.
for 변수 in 리스트[0::2]:
  print(변수)

# range()를 사용한 방법
for 변수 in range(0, len(리스트), 2):
  print(리스트[변수])

가
다
가
다

20

리스트에는 네 개의 문자열이 바인딩돼 있다.

```
리스트 = ["가", "나", "다", "라"]
```
for문을 사용해서 다음과 같이 출력하라.
```
라
다
나
가
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["가", "나", "다", "라"]
# 리스트의 요소를 뒤에서 앞까지 출력한다.
for 변수 in 리스트[::-1]:
  print(변수)

# range()를 사용한 방법
for 변수 in range(len(리스트) - 1, -1, -1):
  print(리스트[변수])

라
다
나
가
라
다
나
가

21

리스트에는 네 개의 정수가 저장돼 있다.

```
리스트 = [3, -20, -3, 44]
```

for문을 사용해서 리스트의 음수를 출력하라.
```
-20
-3
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [3, -20, -3, 44]
for 변수 in 리스트:
  # 0보다 작으면 음수이다.
  if 변수 < 0:
    print(변수)

-20
-3

22

for문을 사용해서 3의 배수만을 출력하라.

```
리스트 = [3, 100, 23, 44]
```
```
3
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [3, 100, 23, 44]
for 변수 in 리스트:
  # 변수를 3으로 나눌 경우 나머지가 0이면 3의 배수이다.
  if 변수 % 3 == 0:
    print(변수)

3

23

리스트에서 20 보다 작은 3의 배수를 출력하라
```
리스트 = [13, 21, 12, 14, 30, 18]
```
```
12
18
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = [13, 21, 12, 14, 30, 18]
for 변수 in 리스트:
  # 변수를 3으로 나눌 경우 나머지가 0이면 3의 배수이다.
  # 20보다 작은 변수를 출력한다.
  if 변수 % 3 == 0 and 변수 < 20:
    print(변수)

12
18

24

리스트에서 세 글자 이상의 문자를 화면에 출력하라

```
리스트 = ["I", "study", "python", "language", "!"]
```
```
study
python
language
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["I", "study", "python", "language", "!"]
for 변수 in 리스트:
  # 변수의 길이가 3 이상일 경우 출력한다.
  if len(변수) >= 3:
    print(변수)

study
python
language

25

리스트에서 대문자만 화면에 출력하라.

```
리스트 = ["A", "b", "c", "D"]
```
```
A
D
```
(참고) isupper() 메서드는 대문자 여부를 판별합니다.
```
>> 변수 = "A"
>> 변수.isupper()
True
>> 변수 = "a"
>> 변수.isupper()
False
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["A", "b", "c", "D"]
for 변수 in 리스트:
  # isupper() : 대문자 여부 판별 (True or False)
  # 변수가 대문자일 경우 출력한다.
  if 변수.isupper():
    print(변수)

A
D

26

리스트에서 소문자만 화면에 출력하라.

```
리스트 = ["A", "b", "c", "D"]
```
```
b
c
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ["A", "b", "c", "D"]
for 변수 in 리스트:
  # islower() : 소문자 여부 판별 (True or False)
  # 변수가 소문자일 경우 출력한다.
  if 변수.islower():
    print(변수)

b
c

27

이름의 첫 글자를 대문자로 변경해서 출력하라.

```
리스트 = ['dog', 'cat', 'parrot']
```
```
Dog
Cat
Parrot
```
(참고) upper() 메서드는 문자열을 대문자로 변경합니다.
```
>> 변수 = "a"
>> a.upper()
A
>> 변수 = "abc"
>> 변수.upper()
ABC
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['dog', 'cat', 'parrot']
for 변수 in 리스트:
  # upper() : 대문자 변환
  # 변수의 첫 글자 (대문자 변환) + 변수의 두 번째 글자부터 출력한다.
  print(변수[0].upper() + 변수[1:])

Dog
Cat
Parrot

28

파일 이름이 저장된 리스트에서 확장자를 제거하고 파일 이름만 화면에 출력하라. (힌트: split() 메서드)

```
리스트 = ['hello.py', 'ex01.py', 'intro.hwp']
```
```
hello
ex01
intro
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['hello.py', 'ex01.py', 'intro.hwp']
for 변수 in 리스트:
  # split() : 분리 후 리스트로 변환
  # .을 기준으로 분리한다.
  split = 변수.split(".") # ['hello', 'py'], ['ex01', 'py'], ['intro', 'hwp']
  # split 리스트 내 요소 중 파일명에 해당하는 요소를 출력한다.
  print(split[0])

hello
ex01
intro

29
파일 이름이 저장된 리스트에서 확장자가 .h인 파일 이름을 출력하라.

```
리스트 = ['intra.h', 'intra.c', 'define.h', 'run.py']
```
```
intra.h
define.h
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['intra.h', 'intra.c', 'define.h', 'run.py']
for 변수 in 리스트:
  # split() : 분리 후 리스트로 변환
  # .을 기준으로 분리한다.
  split = 변수.split(".") # 'intra', 'h'], ['intra', 'c'], ['define', 'h'], ['run', 'py']
  # split 리스트 내 요소 중 확장자에 해당하는 요소를 출력한다. ("h")
  if split[1] == "h":
    print(변수)

intra.h
define.h

30
파일 이름이 저장된 리스트에서 확장자가 .h나 .c인 파일을 화면에 출력하라.

```
리스트 = ['intra.h', 'intra.c', 'define.h', 'run.py']
```
```
intra.h
intra.c
define.h
```

In [ ]:
# 리스트 내 요소를 하나씩 출력한다.
리스트 = ['intra.h', 'intra.c', 'define.h', 'run.py']
for 변수 in 리스트:
  # split() : 분리 후 리스트로 변환
  # .을 기준으로 분리한다.
  split = 변수.split(".") # 'intra', 'h'], ['intra', 'c'], ['define', 'h'], ['run', 'py']
  # split 리스트 내 요소 중 확장자에 해당하는 요소를 출력한다. ("h" or "c")
  if split[1] == "h" or split[1] == "c":
    print(변수)

intra.h
intra.c
define.h

31

for문과 range 구문을 사용해서 0~99까지 한 라인에 하나씩 순차적으로 출력하는 프로그램을 작성하라.

In [ ]:
# range() : 범위
# i를 0~99 범위까지 반복하여 출력한다.
for i in range(100):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

32

월드컵은 4년에 한 번 개최된다. range()를 사용하여 2002~2050년까지 중 월드컵이 개최되는 연도를 출력하라.

```
2002
2006
2010
...
2042
2046
2050
```
참고) range의 세번 째 파라미터는 증감폭을 결정합니다.
```
>> print(list(range(0, 10, 2)))
[0, 2, 4, 6, 8]
```

In [ ]:
# i를 2002~2050 범위까지 반복하여 출력한다.
# 월드컵은 4년에 한 번 개최되므로 증감폭은 4를 준다.
for i in range(2002, 2051, 4):
  print(i)

2002
2006
2010
2014
2018
2022
2026
2030
2034
2038
2042
2046
2050

33

1부터 30까지의 숫자 중 3의 배수를 출력하라.

```
3 
6 
9 
12 
15 
18 
21 
24 
27 
30
```

In [ ]:
# range() : 범위
# i를 3~30 범위까지 반복하여 출력한다.
# 3의 배수를 출력하므로 증감폭은 3을 준다.
for i in range(3, 31, 3):
  print(i)

# i를 1~30 범위까지 반복하여 출력한다.
# 조건문을 통해 3의 배수를 출력한다.
for i in range(1, 31):
  if i % 3 == 0:
    print(i)

3
6
9
12
15
18
21
24
27
30
3
6
9
12
15
18
21
24
27
30

34

99부터 0까지 1씩 감소하는 숫자들을, 한 라인에 하나씩 출력하라.

In [ ]:
# i를 0~99 범위까지 반복하여 출력한다.
# 99에서 i를 빼면 거꾸로 출력된다. (99 - 0, 99 - 1, ...)
for i in range(100):
  print(99 - i)

99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0

35

for문을 사용해서 아래와 같이 출력하라.

```
0.0
0.1
0.2
0.3
0.4
0.5
...
0.9
```

In [ ]:
# i를 0~9 범위까지 반복하여 출력한다.
# i를 10으로 나누면 실수형 값이 반환된다.
for i in range(10):
  print(i / 10)

0.0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9

36

구구단 3단을 출력하라.
```
3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
```

In [ ]:
# i를 1~10 범위까지 반복하여 출력한다.
# f 포맷팅을 사용하여 3xi에 i값을 넣는다.
for i in range(1, 10):
  print(f"3x{i}", "=", 3 * i)

3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27

37

구구단 3단을 출력하라. 단 홀수 번째만 출력한다.

```
3x1 = 3
3x3 = 9
3x5 = 15
3x7 = 21
3x9 = 27
```

In [ ]:
# i를 1~10 범위까지 반복하여 출력한다.
# f 포맷팅을 사용하여 3xi에 i값을 넣는다.
# 조건문을 통해 홀수를 출력한다. (i를 2로 나눌 경우 나머지가 0이 아니면 홀수)
for i in range(1, 10):
  if i % 2 != 0:
    print(f"3x{i}", "=", 3 * i)

3x1 = 3
3x3 = 9
3x5 = 15
3x7 = 21
3x9 = 27

38

1~10까지의 숫자에 대해 모두 더한 값을 출력하는 프로그램을 for 문을 사용하여 작성하라.

```
합 : 55
```

In [ ]:
# sum 초기화
sum = 0
# i를 1~10 범위까지 반복한다.
for i in range(1, 11):
  # sum에 i값 더하며 반복한다.
  sum = sum + i
# sum 출력
print(sum)

55

39

1~10까지의 숫자 중 모든 홀수의 합을 출력하는 프로그램을 for 문을 사용하여 작성하라.

```
합: 25
```

In [ ]:
# sum 초기화
sum = 0
# i를 1~10 범위까지 반복한다.
for i in range(1, 11):
  # 조건문을 통해 홀수를 출력한다. (i를 2로 나눌 경우 나머지가 0이 아니면 홀수)
  if i % 2 != 0:
    # sum에 i값 더하며 반복한다.
    sum = sum + i
# sum 출력
print(sum)

25

40

1~10까지의 숫자를 모두 곱한 값을 출력하는 프로그램을 for 문을 사용하여 작성하라.

In [ ]:
# sum 초기화 (0부터 시작하면 모든 값이 0이 되므로 1부터 시작)
sum = 1
# i를 1~10 범위까지 반복한다.
for i in range(1, 11):
  # sum에 i값 곱하며 반복한다.
  sum = sum * i
# sum 출력
print(sum)

3628800

41

아래와 같이 리스트의 데이터를 출력하라. 단, for문과 range문을 사용하라.
```
price_list = [32100, 32150, 32000, 32500]
32100
32150
32000
32500
```

In [ ]:
# price_list의 요소 개수만큼 반복하여 출력한다.
# price_list[i] 인덱스 번호 0부터 리스트 요소 개수만큼 반복한다.
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
  print(price_list[i])

32100
32150
32000
32500

42

아래와 같이 리스트의 데이터를 출력하라. 단, for문과 range문을 사용하라.

```
price_list = [32100, 32150, 32000, 32500]
0 32100
1 32150
2 32000
3 32500
```

In [ ]:
# price_list의 요소 개수만큼 반복하여 출력한다.
# price_list[i] 인덱스 번호 0부터 리스트 요소 개수만큼 반복한다.
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
  print(i, price_list[i])

0 32100
1 32150
2 32000
3 32500

43

아래와 같이 리스트의 데이터를 출력하라. 단, for문과 range문을 사용하라.

```
price_list = [32100, 32150, 32000, 32500]
3 32100
2 32150
1 32000
0 32500
```

In [ ]:
# price_list의 요소 개수만큼 반복하여 출력한다.
# price_list[i] 인덱스 번호 0부터 리스트 요소 개수만큼 반복한다.
# len(price_list) - i - 1 : 인덱스 번호를 뒤에서 가져오려면 요소의 개수에서 i를 뺀다.
# - 1을 하는 이유는 인덱스 번호는 0부터 시작하기 때문이다.
price_list = [32100, 32150, 32000, 32500]
for i in range(len(price_list)):
  print(len(price_list) - i - 1, price_list[i])

3 32100
2 32150
1 32000
0 32500

44

아래와 같이 리스트의 데이터를 출력하라. 단, for문과 range문을 사용하라.

```
price_list = [32100, 32150, 32000, 32500]
100 32150
110 32000
120 32500
```

In [ ]:
# price_list의 요소 개수만큼 반복하여 출력한다.
# price_list[i] 인덱스 번호 1부터 리스트 요소 개수만큼 반복한다.
# i * 10 + 90
price_list = [32100, 32150, 32000, 32500]
for i in range(1, len(price_list)):
  print(i * 10 + 90, price_list[i])

100 32150
110 32000
120 32500

45

my_list를 아래와 같이 출력하라.

```
my_list = ["가", "나", "다", "라"]
가 나
나 다
다 라
```

In [ ]:
# my_list의 요소 개수만큼 반복하여 출력한다.
# my_list[i] 인덱스 번호 0부터 리스트 요소 개수 - 1만큼 반복한다.
# 왼쪽은 인덱스 번호 0부터, 오른쪽은 인덱스 번호 1부터 시작한다.
my_list = ["가", "나", "다", "라"]
for i in range(len(my_list) - 1):
  print(my_list[i], my_list[i + 1])

가 나
나 다
다 라

46

리스트를 아래와 같이 출력하라.

```
my_list = ["가", "나", "다", "라", "마"]
가 나 다
나 다 라
다 라 마
```

In [ ]:
# my_list의 요소 개수만큼 반복하여 출력한다.
# my_list[i] 인덱스 번호 0부터 리스트 요소 개수 - 2만큼 반복한다.
# 왼쪽은 인덱스 번호 0부터, 가운데는 인덱스 번호 1부터, 오른쪽은 인덱스 번호 2부터 시작한다.
my_list = ["가", "나", "다", "라", "마"]
for i in range(len(my_list) - 2):
  print(my_list[i], my_list[i + 1], my_list[i + 2])

가 나 다
나 다 라
다 라 마

47

반복문과 range 함수를 사용해서 my_list를 아래와 같이 출력하라.

```
my_list = ["가", "나", "다", "라"]
라 다
다 나
나 가
```

In [ ]:
# my_list의 요소 개수만큼 반복하여 출력한다.
# my_list[i] 리스트 요소 개수 - 1부터 인덱스 번호 0만큼 반복한다.
# 스텝을 -1로 주면 역순으로 출력한다.
# 왼쪽은 인덱스 번호 3부터, 오른쪽은 인덱스 번호 2부터 시작한다.
my_list = ["가", "나", "다", "라"]
for i in range(len(my_list) - 1, 0, -1):
  print(my_list[i], my_list[i - 1])

라 다
다 나
나 가

48

리스트에는 네 개의 정수가 저장되어 있다. 각각의 데이터에 대해서 자신과 우측값과의 차분값을 화면에 출력하라.

```
my_list = [100, 200, 400, 800]
```
예를들어 100을 기준으로 우측에 위치한 200과의 차분 값를 화면에 출력하고, 200을 기준으로 우측에 위치한 400과의 차분값을 화면에 출력한다. 이어서 400을 기준으로 우측에 위치한 800과의 차분값을 화면에 출력한다.
```
100
200
400
```

In [ ]:
# my_list의 요소 개수만큼 반복하여 출력한다.
# my_list[i] 인덱스 번호 0부터 리스트 요소 개수 - 1만큼 반복한다.
# 우측값 - 좌측값
my_list = [100, 200, 400, 800]
for i in range(len(my_list) - 1):
  print(my_list[i + 1] - my_list[i])

100
200
400

49

리스트에는 6일 간의 종가 데이터가 저장되어 있다. 종가 데이터의 3일 이동 평균을 계산하고 이를 화면에 출력하라.

```
my_list = [100, 200, 400, 800, 1000, 1300]
```
첫 번째 줄에는 100, 200, 400의 평균값이 출력된다. 두 번째 줄에는 200, 400, 800의 평균값이 출력된다. 같은 방식으로 나머지 데이터의 평균을 출력한다.
```
233.33333333333334
466.6666666666667
733.3333333333334
1033.3333333333333
```

In [ ]:
# my_list의 요소 개수만큼 반복하여 출력한다.
# my_list[i] 인덱스 번호 1부터 리스트 요소 개수 - 1만큼 반복한다.
my_list = [100, 200, 400, 800, 1000, 1300]
for i in range(1, len(my_list) - 1):
  print(my_list[i - 1] + my_list[i] + my_list[i + 1] / 3) # my_list[0] + my_list[1] + my_list[2] / 3

433.33333333333337
866.6666666666667
1533.3333333333333
2233.3333333333335

50

리스트에 5일간의 저가, 고가 정보가 저장돼 있다. 고가와 저가의 차를 변동폭이라고 정의할 때, low, high 두 개의 리스트를 사용해서 5일간의 변동폭을 volatility 리스트에 저장하라.

```
low_prices  = [100, 200, 400, 800, 1000]
high_prices = [150, 300, 430, 880, 1000]
```

In [ ]:
low_prices  = [100, 200, 400, 800, 1000]
high_prices = [150, 300, 430, 880, 1000]
volatility = [] # 변동폭

# low_prices의 요소 개수만큼 반복하여 출력한다.
# append() : 리스트에 요소 추가
# 변동폭 = 고가 - 저가 (volatility = high_prices[i] - low_prices[i])
for i in range(len(low_prices)):
  volatility.append(high_prices[i] - low_prices[i])
print(volatility)

[50, 100, 30, 80, 0]